name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm i
      - run: npm run build
      - run: npm i -g surge
      - run: surge ./build/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
